/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShowroomSlugRouteImport } from './routes/showroom.$slug'
import { Route as AdminProyectosIndexRouteImport } from './routes/admin.proyectos.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShowroomSlugRoute = ShowroomSlugRouteImport.update({
  id: '/showroom/$slug',
  path: '/showroom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProyectosIndexRoute = AdminProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/proyectos': typeof AdminProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/showroom/$slug' | '/admin/' | '/admin/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/showroom/$slug' | '/admin' | '/admin/proyectos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/showroom/$slug'
    | '/admin/'
    | '/admin/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ShowroomSlugRoute: typeof ShowroomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/showroom/$slug': {
      id: '/showroom/$slug'
      path: '/showroom/$slug'
      fullPath: '/showroom/$slug'
      preLoaderRoute: typeof ShowroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proyectos/': {
      id: '/admin/proyectos/'
      path: '/proyectos'
      fullPath: '/admin/proyectos/'
      preLoaderRoute: typeof AdminProyectosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProyectosIndexRoute: typeof AdminProyectosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProyectosIndexRoute: AdminProyectosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ShowroomSlugRoute: ShowroomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
