/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminUnidadesRouteImport } from './routes/admin.unidades'
import { Route as ShowroomSlugRouteImport } from './routes/showroom.$slug'
import { Route as AdminProyectosIndexRouteImport } from './routes/admin.proyectos.index'
import { Route as AdminProyectosSlugRouteImport } from './routes/admin.proyectos.$slug'
import { Route as ShowroomSlugIndexRouteImport } from './routes/showroom.$slug.index'
import { Route as ShowroomSlugTourRouteImport } from './routes/showroom.$slug.tour'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnidadesRoute = AdminUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AdminRoute,
} as any)
const ShowroomSlugRoute = ShowroomSlugRouteImport.update({
  id: '/showroom/$slug',
  path: '/showroom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProyectosIndexRoute = AdminProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosSlugRoute = AdminProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const ShowroomSlugIndexRoute = ShowroomSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowroomSlugRoute,
} as any)
const ShowroomSlugTourRoute = ShowroomSlugTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => ShowroomSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/showroom/$slug': typeof ShowroomSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/$slug': typeof AdminProyectosSlugRoute
  '/showroom/$slug/tour': typeof ShowroomSlugTourRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/showroom/$slug/': typeof ShowroomSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/proyectos/$slug': typeof AdminProyectosSlugRoute
  '/showroom/$slug/tour': typeof ShowroomSlugTourRoute
  '/admin/proyectos': typeof AdminProyectosIndexRoute
  '/showroom/$slug': typeof ShowroomSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/showroom/$slug': typeof ShowroomSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/$slug': typeof AdminProyectosSlugRoute
  '/showroom/$slug/tour': typeof ShowroomSlugTourRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/showroom/$slug/': typeof ShowroomSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/configuracion'
    | '/admin/leads'
    | '/admin/unidades'
    | '/showroom/$slug'
    | '/admin/'
    | '/admin/proyectos/$slug'
    | '/showroom/$slug/tour'
    | '/admin/proyectos/'
    | '/showroom/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/configuracion'
    | '/admin/leads'
    | '/admin/unidades'
    | '/admin'
    | '/admin/proyectos/$slug'
    | '/showroom/$slug/tour'
    | '/admin/proyectos'
    | '/showroom/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/configuracion'
    | '/admin/leads'
    | '/admin/unidades'
    | '/showroom/$slug'
    | '/admin/'
    | '/admin/proyectos/$slug'
    | '/showroom/$slug/tour'
    | '/admin/proyectos/'
    | '/showroom/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ShowroomSlugRoute: typeof ShowroomSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unidades': {
      id: '/admin/unidades'
      path: '/unidades'
      fullPath: '/admin/unidades'
      preLoaderRoute: typeof AdminUnidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/showroom/$slug': {
      id: '/showroom/$slug'
      path: '/showroom/$slug'
      fullPath: '/showroom/$slug'
      preLoaderRoute: typeof ShowroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proyectos/': {
      id: '/admin/proyectos/'
      path: '/proyectos'
      fullPath: '/admin/proyectos/'
      preLoaderRoute: typeof AdminProyectosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/$slug': {
      id: '/admin/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/admin/proyectos/$slug'
      preLoaderRoute: typeof AdminProyectosSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/showroom/$slug/': {
      id: '/showroom/$slug/'
      path: '/'
      fullPath: '/showroom/$slug/'
      preLoaderRoute: typeof ShowroomSlugIndexRouteImport
      parentRoute: typeof ShowroomSlugRoute
    }
    '/showroom/$slug/tour': {
      id: '/showroom/$slug/tour'
      path: '/tour'
      fullPath: '/showroom/$slug/tour'
      preLoaderRoute: typeof ShowroomSlugTourRouteImport
      parentRoute: typeof ShowroomSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminUnidadesRoute: typeof AdminUnidadesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProyectosSlugRoute: typeof AdminProyectosSlugRoute
  AdminProyectosIndexRoute: typeof AdminProyectosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminUnidadesRoute: AdminUnidadesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProyectosSlugRoute: AdminProyectosSlugRoute,
  AdminProyectosIndexRoute: AdminProyectosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShowroomSlugRouteChildren {
  ShowroomSlugTourRoute: typeof ShowroomSlugTourRoute
  ShowroomSlugIndexRoute: typeof ShowroomSlugIndexRoute
}

const ShowroomSlugRouteChildren: ShowroomSlugRouteChildren = {
  ShowroomSlugTourRoute: ShowroomSlugTourRoute,
  ShowroomSlugIndexRoute: ShowroomSlugIndexRoute,
}

const ShowroomSlugRouteWithChildren = ShowroomSlugRoute._addFileChildren(
  ShowroomSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ShowroomSlugRoute: ShowroomSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
